using System;
using System.Collections.Generic;
using System.Xml;
using System.Xml.Serialization;

namespace RTSDotNETClient.WSRE
{

    /// <summary>
    /// The request reply type
    /// </summary>
    public enum RequestReplyType
    {
        /// <summary>
        /// Not specified, cannot be sent to the web service
        /// </summary>
        [XmlEnum("0")]
        NotSpecified = 0,

        /// <summary>
        /// The data sent with this reply is the correct data
        /// </summary>
        [XmlEnum("1")]
        DataSentWithThisReplyIsTheCorrectData=1,
        
        /// <summary>
        /// The data sent before was sent in error and should be deleted
        /// </summary>
        [XmlEnum("2")]
        DataSentBeforeShouldBeDeleted=2,

        /// <summary>
        /// There is no termination data available
        /// </summary>
        [XmlEnum("3")]
        NoTerminationDataAvailable=3
    }

    /// <summary>
    /// The query object to be sent to the WSRE web service
    /// </summary>
    [XmlRoot("SafeTIR", Namespace = "http://www.iru.org/SafeTIRUpload")]
    public class Query : BaseQueryResponse
    {
        /// <summary>
        /// The xml schema definition file that defines the structure of the query
        /// </summary>
        public const string Xsd = "SafeTIRUpload.xsd";

        /// <summary>
        /// The body of the query
        /// </summary>
        public Body Body = new Body();

        /// <summary>
        /// Customs Authorities Internal Value, not used by the IRU
        /// </summary>
        [XmlAttribute("Sender_Document_Version")]
        public string SenderDocumentVersion { get; set; }

        /// <summary>
        /// The default constructor
        /// </summary>
        public Query()
        {
            this.xsd = Xsd;
        }
    }

    /// <summary>
    /// The query body
    /// </summary>
    public class Body
    {
        /// <summary>
        /// Total Number of Reconciliation Request Reply records sent in this message
        /// </summary>
        public int NumberOfRecords { get; set; }

        /// <summary>
        /// The set of Reconciliation Request Reply Records Uploaded
        /// </summary>
        public List<RequestReplyRecord> RequestReplyRecords { get; set; }
    }

    /// <summary>
    /// One Reconciliation Request Reply Record
    /// </summary>
    public class RequestReplyRecord
    {
        /// <summary>
        /// Unique identifier generated by the IRU.
        /// </summary>
        [XmlAttribute("RequestID")]
        public string RequestID { get; set; }
        
        /// <summary>
        /// The request reply type
        /// </summary>
        [XmlAttribute("RequestReplyType")]
        public RequestReplyType RequestReplyType { get; set; }
        
        /// <summary>
        /// TIR Carnet Reference Number
        /// </summary>
        [XmlAttribute("TNO")]
        public string TNO { get; set; }
        
        /// <summary>
        /// ISO3 code of the country of termination
        /// </summary>
        [XmlAttribute("ICC")]
        public string ICC { get; set; }
        
        /// <summary>
        /// Date in Customs Ledger (Termination)
        /// </summary>
        [XmlAttribute("DCL", DataType = "date")]
        public DateTime DCL { get; set; }
        
        /// <summary>
        /// Record Number in Customs Ledger (Termination)
        /// </summary>
        [XmlAttribute("CNL")]
        public string CNL { get; set; }
        
        /// <summary>
        /// Name or Number of Customs Office
        /// </summary>
        [XmlAttribute("COF")]
        public string COF { get; set; }
        
        /// <summary>
        /// Date of Discharge
        /// </summary>
        [XmlAttribute("DDI", DataType = "date")]
        public DateTime DDI { get; set; }
        
        /// <summary>
        /// Reference Number of Discharge
        /// </summary>
        [XmlAttribute("RND")]
        public string RND { get; set; }
        
        /// <summary>
        /// Partial/Final Discharge
        /// </summary>
        [XmlAttribute("PFD")]
        public string PFD { get; set; }
        
        /// <summary>
        /// Discharge with or without Reservation.
        /// <remarks>If Discharge is without reservation, the string "OK" will be used; if with Reservation, one character string, "R", will be used.</remarks>
        /// </summary>
        [XmlAttribute("CWR")]
        public CWR CWR { get; set; }
        
        /// <summary>
        /// Volet Page Number. This field contains the page number of the volet pertaining to the discharge and must be an even number in the range 2 to 20 (inclusive).
        /// </summary>
        [XmlAttribute("VPN")]
        public int VPN { get; set; }
        
        /// <summary>
        /// A comment
        /// </summary>
        [XmlAttribute("COM")]
        public string COM { get; set; }
        
        /// <summary>
        /// Carnet / Volet retained or not by Customs
        /// </summary>
        [XmlAttribute("RBC")]
        public RBC RBC { get; set; }
        
        /// <summary>
        /// Number of packages unloaded
        /// </summary>
        [XmlAttribute("PIC")]
        public int PIC { get; set; }
    }

}
