//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTSDotNETClient.ReconciliationWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReconciliationQuery", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class ReconciliationQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ReconciliationQueryDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sender_MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information_Exchange_VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ReconciliationQueryData {
            get {
                return this.ReconciliationQueryDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ReconciliationQueryDataField, value) != true)) {
                    this.ReconciliationQueryDataField = value;
                    this.RaisePropertyChanged("ReconciliationQueryData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sender_MessageID {
            get {
                return this.Sender_MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.Sender_MessageIDField, value) != true)) {
                    this.Sender_MessageIDField = value;
                    this.RaisePropertyChanged("Sender_MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Information_Exchange_Version {
            get {
                return this.Information_Exchange_VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.Information_Exchange_VersionField, value) != true)) {
                    this.Information_Exchange_VersionField = value;
                    this.RaisePropertyChanged("Information_Exchange_Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReconciliationResponse", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class ReconciliationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ReconciliationRequestDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sender_MessageIDField;
        
        private int ReturnCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] ReconciliationRequestData {
            get {
                return this.ReconciliationRequestDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ReconciliationRequestDataField, value) != true)) {
                    this.ReconciliationRequestDataField = value;
                    this.RaisePropertyChanged("ReconciliationRequestData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sender_MessageID {
            get {
                return this.Sender_MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.Sender_MessageIDField, value) != true)) {
                    this.Sender_MessageIDField = value;
                    this.RaisePropertyChanged("Sender_MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iru.org", ConfigurationName="ReconciliationWS.ReconciliationQueryServiceClassSoap")]
    public interface ReconciliationQueryServiceClassSoap {
        
        // CODEGEN: Generating message contract since element name su from namespace http://www.iru.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iru.org/WSRQ", ReplyAction="*")]
        RTSDotNETClient.ReconciliationWS.WSRQResponse WSRQ(RTSDotNETClient.ReconciliationWS.WSRQRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSRQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSRQ", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.ReconciliationWS.WSRQRequestBody Body;
        
        public WSRQRequest() {
        }
        
        public WSRQRequest(RTSDotNETClient.ReconciliationWS.WSRQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSRQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.ReconciliationWS.ReconciliationQuery su;
        
        public WSRQRequestBody() {
        }
        
        public WSRQRequestBody(RTSDotNETClient.ReconciliationWS.ReconciliationQuery su) {
            this.su = su;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSRQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSRQResponse", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.ReconciliationWS.WSRQResponseBody Body;
        
        public WSRQResponse() {
        }
        
        public WSRQResponse(RTSDotNETClient.ReconciliationWS.WSRQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSRQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.ReconciliationWS.ReconciliationResponse WSRQResult;
        
        public WSRQResponseBody() {
        }
        
        public WSRQResponseBody(RTSDotNETClient.ReconciliationWS.ReconciliationResponse WSRQResult) {
            this.WSRQResult = WSRQResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReconciliationQueryServiceClassSoapChannel : RTSDotNETClient.ReconciliationWS.ReconciliationQueryServiceClassSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReconciliationQueryServiceClassSoapClient : System.ServiceModel.ClientBase<RTSDotNETClient.ReconciliationWS.ReconciliationQueryServiceClassSoap>, RTSDotNETClient.ReconciliationWS.ReconciliationQueryServiceClassSoap {
        
        public ReconciliationQueryServiceClassSoapClient() {
        }
        
        public ReconciliationQueryServiceClassSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReconciliationQueryServiceClassSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReconciliationQueryServiceClassSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReconciliationQueryServiceClassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RTSDotNETClient.ReconciliationWS.WSRQResponse RTSDotNETClient.ReconciliationWS.ReconciliationQueryServiceClassSoap.WSRQ(RTSDotNETClient.ReconciliationWS.WSRQRequest request) {
            return base.Channel.WSRQ(request);
        }
        
        public RTSDotNETClient.ReconciliationWS.ReconciliationResponse WSRQ(RTSDotNETClient.ReconciliationWS.ReconciliationQuery su) {
            RTSDotNETClient.ReconciliationWS.WSRQRequest inValue = new RTSDotNETClient.ReconciliationWS.WSRQRequest();
            inValue.Body = new RTSDotNETClient.ReconciliationWS.WSRQRequestBody();
            inValue.Body.su = su;
            RTSDotNETClient.ReconciliationWS.WSRQResponse retVal = ((RTSDotNETClient.ReconciliationWS.ReconciliationQueryServiceClassSoap)(this)).WSRQ(inValue);
            return retVal.Body.WSRQResult;
        }
    }
}
