//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2G.G2B {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIREPDG2BUploadParams", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class TIREPDG2BUploadParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SubscriberIDField;
        
        private string CertificateIDField;
        
        private byte[] ESessionKeyField;
        
        private string SubscriberMessageIDField;
        
        private string InformationExchangeVersionField;
        
        private string MessageNameField;
        
        private System.DateTime TimeSentField;
        
        private byte[] MessageContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string CertificateID {
            get {
                return this.CertificateIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateIDField, value) != true)) {
                    this.CertificateIDField = value;
                    this.RaisePropertyChanged("CertificateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string SubscriberMessageID {
            get {
                return this.SubscriberMessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberMessageIDField, value) != true)) {
                    this.SubscriberMessageIDField = value;
                    this.RaisePropertyChanged("SubscriberMessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public string InformationExchangeVersion {
            get {
                return this.InformationExchangeVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationExchangeVersionField, value) != true)) {
                    this.InformationExchangeVersionField = value;
                    this.RaisePropertyChanged("InformationExchangeVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public string MessageName {
            get {
                return this.MessageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageNameField, value) != true)) {
                    this.MessageNameField = value;
                    this.RaisePropertyChanged("MessageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime TimeSent {
            get {
                return this.TimeSentField;
            }
            set {
                if ((this.TimeSentField.Equals(value) != true)) {
                    this.TimeSentField = value;
                    this.RaisePropertyChanged("TimeSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public byte[] MessageContent {
            get {
                return this.MessageContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageContentField, value) != true)) {
                    this.MessageContentField = value;
                    this.RaisePropertyChanged("MessageContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIREPDG2BUploadAck", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class TIREPDG2BUploadAck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberMessageIDField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReturnCodeReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HostID {
            get {
                return this.HostIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HostIDField, value) != true)) {
                    this.HostIDField = value;
                    this.RaisePropertyChanged("HostID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubscriberMessageID {
            get {
                return this.SubscriberMessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberMessageIDField, value) != true)) {
                    this.SubscriberMessageIDField = value;
                    this.RaisePropertyChanged("SubscriberMessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ReturnCodeReason {
            get {
                return this.ReturnCodeReasonField;
            }
            set {
                if ((this.ReturnCodeReasonField.Equals(value) != true)) {
                    this.ReturnCodeReasonField = value;
                    this.RaisePropertyChanged("ReturnCodeReason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iru.org", ConfigurationName="G2B.TIREPDG2BServiceClassSoap")]
    public interface TIREPDG2BServiceClassSoap {
        
        // CODEGEN: Generating message contract since element name su from namespace http://www.iru.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iru.org/TIREPDG2B", ReplyAction="*")]
        B2G.G2B.TIREPDG2BResponse TIREPDG2B(B2G.G2B.TIREPDG2BRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TIREPDG2BRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TIREPDG2B", Namespace="http://www.iru.org", Order=0)]
        public B2G.G2B.TIREPDG2BRequestBody Body;
        
        public TIREPDG2BRequest() {
        }
        
        public TIREPDG2BRequest(B2G.G2B.TIREPDG2BRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class TIREPDG2BRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2G.G2B.TIREPDG2BUploadParams su;
        
        public TIREPDG2BRequestBody() {
        }
        
        public TIREPDG2BRequestBody(B2G.G2B.TIREPDG2BUploadParams su) {
            this.su = su;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TIREPDG2BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TIREPDG2BResponse", Namespace="http://www.iru.org", Order=0)]
        public B2G.G2B.TIREPDG2BResponseBody Body;
        
        public TIREPDG2BResponse() {
        }
        
        public TIREPDG2BResponse(B2G.G2B.TIREPDG2BResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class TIREPDG2BResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2G.G2B.TIREPDG2BUploadAck TIREPDG2BResult;
        
        public TIREPDG2BResponseBody() {
        }
        
        public TIREPDG2BResponseBody(B2G.G2B.TIREPDG2BUploadAck TIREPDG2BResult) {
            this.TIREPDG2BResult = TIREPDG2BResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TIREPDG2BServiceClassSoapChannel : B2G.G2B.TIREPDG2BServiceClassSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TIREPDG2BServiceClassSoapClient : System.ServiceModel.ClientBase<B2G.G2B.TIREPDG2BServiceClassSoap>, B2G.G2B.TIREPDG2BServiceClassSoap {
        
        public TIREPDG2BServiceClassSoapClient() {
        }
        
        public TIREPDG2BServiceClassSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TIREPDG2BServiceClassSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TIREPDG2BServiceClassSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TIREPDG2BServiceClassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2G.G2B.TIREPDG2BResponse B2G.G2B.TIREPDG2BServiceClassSoap.TIREPDG2B(B2G.G2B.TIREPDG2BRequest request) {
            return base.Channel.TIREPDG2B(request);
        }
        
        public B2G.G2B.TIREPDG2BUploadAck TIREPDG2B(B2G.G2B.TIREPDG2BUploadParams su) {
            B2G.G2B.TIREPDG2BRequest inValue = new B2G.G2B.TIREPDG2BRequest();
            inValue.Body = new B2G.G2B.TIREPDG2BRequestBody();
            inValue.Body.su = su;
            B2G.G2B.TIREPDG2BResponse retVal = ((B2G.G2B.TIREPDG2BServiceClassSoap)(this)).TIREPDG2B(inValue);
            return retVal.Body.TIREPDG2BResult;
        }
    }
}
