//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTSDotNETClient.CarnetHolderQueryWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIRHolderQuery", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class TIRHolderQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TIRCarnetHolderQueryParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Query_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] TIRCarnetHolderQueryParams {
            get {
                return this.TIRCarnetHolderQueryParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.TIRCarnetHolderQueryParamsField, value) != true)) {
                    this.TIRCarnetHolderQueryParamsField = value;
                    this.RaisePropertyChanged("TIRCarnetHolderQueryParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Query_ID {
            get {
                return this.Query_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Query_IDField, value) != true)) {
                    this.Query_IDField = value;
                    this.RaisePropertyChanged("Query_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIRHolderResponse", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class TIRHolderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] TIRCarnetHolderResponseParamsField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Query_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] TIRCarnetHolderResponseParams {
            get {
                return this.TIRCarnetHolderResponseParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.TIRCarnetHolderResponseParamsField, value) != true)) {
                    this.TIRCarnetHolderResponseParamsField = value;
                    this.RaisePropertyChanged("TIRCarnetHolderResponseParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Query_ID {
            get {
                return this.Query_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Query_IDField, value) != true)) {
                    this.Query_IDField = value;
                    this.RaisePropertyChanged("Query_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iru.org", ConfigurationName="CarnetHolderQueryWS.SafeTIRHolderQueryServiceClassSoap")]
    public interface SafeTIRHolderQueryServiceClassSoap {
        
        // CODEGEN: Generating message contract since element name su from namespace http://www.iru.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iru.org/WSTCHQ", ReplyAction="*")]
        RTSDotNETClient.CarnetHolderQueryWS.WSTCHQResponse WSTCHQ(RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSTCHQRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSTCHQ", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequestBody Body;
        
        public WSTCHQRequest() {
        }
        
        public WSTCHQRequest(RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSTCHQRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.CarnetHolderQueryWS.TIRHolderQuery su;
        
        public WSTCHQRequestBody() {
        }
        
        public WSTCHQRequestBody(RTSDotNETClient.CarnetHolderQueryWS.TIRHolderQuery su) {
            this.su = su;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSTCHQResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSTCHQResponse", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.CarnetHolderQueryWS.WSTCHQResponseBody Body;
        
        public WSTCHQResponse() {
        }
        
        public WSTCHQResponse(RTSDotNETClient.CarnetHolderQueryWS.WSTCHQResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSTCHQResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.CarnetHolderQueryWS.TIRHolderResponse WSTCHQResult;
        
        public WSTCHQResponseBody() {
        }
        
        public WSTCHQResponseBody(RTSDotNETClient.CarnetHolderQueryWS.TIRHolderResponse WSTCHQResult) {
            this.WSTCHQResult = WSTCHQResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SafeTIRHolderQueryServiceClassSoapChannel : RTSDotNETClient.CarnetHolderQueryWS.SafeTIRHolderQueryServiceClassSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SafeTIRHolderQueryServiceClassSoapClient : System.ServiceModel.ClientBase<RTSDotNETClient.CarnetHolderQueryWS.SafeTIRHolderQueryServiceClassSoap>, RTSDotNETClient.CarnetHolderQueryWS.SafeTIRHolderQueryServiceClassSoap {
        
        public SafeTIRHolderQueryServiceClassSoapClient() {
        }
        
        public SafeTIRHolderQueryServiceClassSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SafeTIRHolderQueryServiceClassSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SafeTIRHolderQueryServiceClassSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SafeTIRHolderQueryServiceClassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RTSDotNETClient.CarnetHolderQueryWS.WSTCHQResponse RTSDotNETClient.CarnetHolderQueryWS.SafeTIRHolderQueryServiceClassSoap.WSTCHQ(RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequest request) {
            return base.Channel.WSTCHQ(request);
        }
        
        public RTSDotNETClient.CarnetHolderQueryWS.TIRHolderResponse WSTCHQ(RTSDotNETClient.CarnetHolderQueryWS.TIRHolderQuery su) {
            RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequest inValue = new RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequest();
            inValue.Body = new RTSDotNETClient.CarnetHolderQueryWS.WSTCHQRequestBody();
            inValue.Body.su = su;
            RTSDotNETClient.CarnetHolderQueryWS.WSTCHQResponse retVal = ((RTSDotNETClient.CarnetHolderQueryWS.SafeTIRHolderQueryServiceClassSoap)(this)).WSTCHQ(inValue);
            return retVal.Body.WSTCHQResult;
        }
    }
}
