//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTSDotNETClient.SafeTIRUploadWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SafeTIRUploadParams", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class SafeTIRUploadParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] safeTIRUploadDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyToIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sender_MessageIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] safeTIRUploadData {
            get {
                return this.safeTIRUploadDataField;
            }
            set {
                if ((object.ReferenceEquals(this.safeTIRUploadDataField, value) != true)) {
                    this.safeTIRUploadDataField = value;
                    this.RaisePropertyChanged("safeTIRUploadData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CopyToID {
            get {
                return this.CopyToIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyToIDField, value) != true)) {
                    this.CopyToIDField = value;
                    this.RaisePropertyChanged("CopyToID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sender_MessageID {
            get {
                return this.Sender_MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.Sender_MessageIDField, value) != true)) {
                    this.Sender_MessageIDField = value;
                    this.RaisePropertyChanged("Sender_MessageID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SafeTIRUploadAck", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class SafeTIRUploadAck : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        private System.DateTime ResponseTimeField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sender_MessageIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ResponseTime {
            get {
                return this.ResponseTimeField;
            }
            set {
                if ((this.ResponseTimeField.Equals(value) != true)) {
                    this.ResponseTimeField = value;
                    this.RaisePropertyChanged("ResponseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sender_MessageID {
            get {
                return this.Sender_MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.Sender_MessageIDField, value) != true)) {
                    this.Sender_MessageIDField = value;
                    this.RaisePropertyChanged("Sender_MessageID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SafeTIRReconParams", Namespace="http://www.iru.org")]
    [System.SerializableAttribute()]
    public partial class SafeTIRReconParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SafeTIRReconDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sender_MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Information_Exchange_VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] SafeTIRReconData {
            get {
                return this.SafeTIRReconDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SafeTIRReconDataField, value) != true)) {
                    this.SafeTIRReconDataField = value;
                    this.RaisePropertyChanged("SafeTIRReconData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sender_MessageID {
            get {
                return this.Sender_MessageIDField;
            }
            set {
                if ((object.ReferenceEquals(this.Sender_MessageIDField, value) != true)) {
                    this.Sender_MessageIDField = value;
                    this.RaisePropertyChanged("Sender_MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Information_Exchange_Version {
            get {
                return this.Information_Exchange_VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.Information_Exchange_VersionField, value) != true)) {
                    this.Information_Exchange_VersionField = value;
                    this.RaisePropertyChanged("Information_Exchange_Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iru.org", ConfigurationName="SafeTIRUploadWS.SafeTirUploadSoap")]
    public interface SafeTirUploadSoap {
        
        // CODEGEN: Generating message contract since element name su from namespace http://www.iru.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iru.org/WSST", ReplyAction="*")]
        RTSDotNETClient.SafeTIRUploadWS.WSSTResponse WSST(RTSDotNETClient.SafeTIRUploadWS.WSSTRequest request);
        
        // CODEGEN: Generating message contract since element name su from namespace http://www.iru.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.iru.org/WSRE", ReplyAction="*")]
        RTSDotNETClient.SafeTIRUploadWS.WSREResponse WSRE(RTSDotNETClient.SafeTIRUploadWS.WSRERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSSTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSST", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.WSSTRequestBody Body;
        
        public WSSTRequest() {
        }
        
        public WSSTRequest(RTSDotNETClient.SafeTIRUploadWS.WSSTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSSTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadParams su;
        
        public WSSTRequestBody() {
        }
        
        public WSSTRequestBody(RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadParams su) {
            this.su = su;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSSTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSSTResponse", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.WSSTResponseBody Body;
        
        public WSSTResponse() {
        }
        
        public WSSTResponse(RTSDotNETClient.SafeTIRUploadWS.WSSTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSSTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadAck WSSTResult;
        
        public WSSTResponseBody() {
        }
        
        public WSSTResponseBody(RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadAck WSSTResult) {
            this.WSSTResult = WSSTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSRERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSRE", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.WSRERequestBody Body;
        
        public WSRERequest() {
        }
        
        public WSRERequest(RTSDotNETClient.SafeTIRUploadWS.WSRERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSRERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.SafeTIRReconParams su;
        
        public WSRERequestBody() {
        }
        
        public WSRERequestBody(RTSDotNETClient.SafeTIRUploadWS.SafeTIRReconParams su) {
            this.su = su;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WSREResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WSREResponse", Namespace="http://www.iru.org", Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.WSREResponseBody Body;
        
        public WSREResponse() {
        }
        
        public WSREResponse(RTSDotNETClient.SafeTIRUploadWS.WSREResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.iru.org")]
    public partial class WSREResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadAck WSREResult;
        
        public WSREResponseBody() {
        }
        
        public WSREResponseBody(RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadAck WSREResult) {
            this.WSREResult = WSREResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SafeTirUploadSoapChannel : RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SafeTirUploadSoapClient : System.ServiceModel.ClientBase<RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap>, RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap {
        
        public SafeTirUploadSoapClient() {
        }
        
        public SafeTirUploadSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SafeTirUploadSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SafeTirUploadSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SafeTirUploadSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RTSDotNETClient.SafeTIRUploadWS.WSSTResponse RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap.WSST(RTSDotNETClient.SafeTIRUploadWS.WSSTRequest request) {
            return base.Channel.WSST(request);
        }
        
        public RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadAck WSST(RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadParams su) {
            RTSDotNETClient.SafeTIRUploadWS.WSSTRequest inValue = new RTSDotNETClient.SafeTIRUploadWS.WSSTRequest();
            inValue.Body = new RTSDotNETClient.SafeTIRUploadWS.WSSTRequestBody();
            inValue.Body.su = su;
            RTSDotNETClient.SafeTIRUploadWS.WSSTResponse retVal = ((RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap)(this)).WSST(inValue);
            return retVal.Body.WSSTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RTSDotNETClient.SafeTIRUploadWS.WSREResponse RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap.WSRE(RTSDotNETClient.SafeTIRUploadWS.WSRERequest request) {
            return base.Channel.WSRE(request);
        }
        
        public RTSDotNETClient.SafeTIRUploadWS.SafeTIRUploadAck WSRE(RTSDotNETClient.SafeTIRUploadWS.SafeTIRReconParams su) {
            RTSDotNETClient.SafeTIRUploadWS.WSRERequest inValue = new RTSDotNETClient.SafeTIRUploadWS.WSRERequest();
            inValue.Body = new RTSDotNETClient.SafeTIRUploadWS.WSRERequestBody();
            inValue.Body.su = su;
            RTSDotNETClient.SafeTIRUploadWS.WSREResponse retVal = ((RTSDotNETClient.SafeTIRUploadWS.SafeTirUploadSoap)(this)).WSRE(inValue);
            return retVal.Body.WSREResult;
        }
    }
}
