'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'     wsdl.exe https://apps-test.iru.org/RTS2/TIREPDB2G/TIREPDB2GService.asmx?wsdl /l:VB /serverInterface
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="TIREPDB2GServiceClassSoap", [Namespace]:="http://www.iru.org")>  _
Public Interface ITIREPDB2GServiceClassSoap
    
    '''<remarks/>
    <System.Web.Services.WebMethodAttribute(),  _
     System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/TIREPDB2G", RequestNamespace:="http://www.iru.org", ResponseNamespace:="http://www.iru.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Function TIREPDB2G(ByVal su As TIREPDB2GUploadParams) As TIREPDB2GUploadAck
End Interface

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.iru.org")>  _
Partial Public Class TIREPDB2GUploadParams
    
    Private subscriberIDField As String
    
    Private certificateIDField As String
    
    Private eSessionKeyField() As Byte
    
    Private subscriberMessageIDField As String
    
    Private informationExchangeVersionField As String
    
    Private messageNameField As String
    
    Private timeSentField As Date
    
    Private messageContentField() As Byte
    
    '''<remarks/>
    Public Property SubscriberID() As String
        Get
            Return Me.subscriberIDField
        End Get
        Set
            Me.subscriberIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CertificateID() As String
        Get
            Return Me.certificateIDField
        End Get
        Set
            Me.certificateIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property ESessionKey() As Byte()
        Get
            Return Me.eSessionKeyField
        End Get
        Set
            Me.eSessionKeyField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SubscriberMessageID() As String
        Get
            Return Me.subscriberMessageIDField
        End Get
        Set
            Me.subscriberMessageIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InformationExchangeVersion() As String
        Get
            Return Me.informationExchangeVersionField
        End Get
        Set
            Me.informationExchangeVersionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property MessageName() As String
        Get
            Return Me.messageNameField
        End Get
        Set
            Me.messageNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TimeSent() As Date
        Get
            Return Me.timeSentField
        End Get
        Set
            Me.timeSentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property MessageContent() As Byte()
        Get
            Return Me.messageContentField
        End Get
        Set
            Me.messageContentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.iru.org")>  _
Partial Public Class TIREPDB2GUploadAck
    
    Private hostIDField As String
    
    Private subscriberMessageIDField As String
    
    Private returnCodeField As Integer
    
    Private returnCodeReasonField As Integer
    
    Private returnCodeReasonFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property HostID() As String
        Get
            Return Me.hostIDField
        End Get
        Set
            Me.hostIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SubscriberMessageID() As String
        Get
            Return Me.subscriberMessageIDField
        End Get
        Set
            Me.subscriberMessageIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ReturnCode() As Integer
        Get
            Return Me.returnCodeField
        End Get
        Set
            Me.returnCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ReturnCodeReason() As Integer
        Get
            Return Me.returnCodeReasonField
        End Get
        Set
            Me.returnCodeReasonField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ReturnCodeReasonSpecified() As Boolean
        Get
            Return Me.returnCodeReasonFieldSpecified
        End Get
        Set
            Me.returnCodeReasonFieldSpecified = value
        End Set
    End Property
End Class
