'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'     wsdl.exe https://apps-test.iru.org/RTS2/TIREPDG2B/TIREPDG2BService.asmx?wsdl /l:VB
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="TIREPDG2BServiceClassSoap", [Namespace]:="http://www.iru.org")>  _
Partial Public Class TIREPDG2BService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private TIREPDG2BOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "https://apps-test.iru.org/RTS2/TIREPDG2B/TIREPDG2BService.asmx"
    End Sub
    
    '''<remarks/>
    Public Event TIREPDG2BCompleted As TIREPDG2BCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.iru.org/TIREPDG2B", RequestNamespace:="http://www.iru.org", ResponseNamespace:="http://www.iru.org", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function TIREPDG2B(ByVal su As TIREPDG2BUploadParams) As TIREPDG2BUploadAck
        Dim results() As Object = Me.Invoke("TIREPDG2B", New Object() {su})
        Return CType(results(0),TIREPDG2BUploadAck)
    End Function
    
    '''<remarks/>
    Public Function BeginTIREPDG2B(ByVal su As TIREPDG2BUploadParams, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("TIREPDG2B", New Object() {su}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndTIREPDG2B(ByVal asyncResult As System.IAsyncResult) As TIREPDG2BUploadAck
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),TIREPDG2BUploadAck)
    End Function
    
    '''<remarks/>
    Public Overloads Sub TIREPDG2BAsync(ByVal su As TIREPDG2BUploadParams)
        Me.TIREPDG2BAsync(su, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub TIREPDG2BAsync(ByVal su As TIREPDG2BUploadParams, ByVal userState As Object)
        If (Me.TIREPDG2BOperationCompleted Is Nothing) Then
            Me.TIREPDG2BOperationCompleted = AddressOf Me.OnTIREPDG2BOperationCompleted
        End If
        Me.InvokeAsync("TIREPDG2B", New Object() {su}, Me.TIREPDG2BOperationCompleted, userState)
    End Sub
    
    Private Sub OnTIREPDG2BOperationCompleted(ByVal arg As Object)
        If (Not (Me.TIREPDG2BCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent TIREPDG2BCompleted(Me, New TIREPDG2BCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.iru.org")>  _
Partial Public Class TIREPDG2BUploadParams
    
    Private subscriberIDField As String
    
    Private certificateIDField As String
    
    Private eSessionKeyField() As Byte
    
    Private subscriberMessageIDField As String
    
    Private informationExchangeVersionField As String
    
    Private messageNameField As String
    
    Private timeSentField As Date
    
    Private messageContentField() As Byte
    
    '''<remarks/>
    Public Property SubscriberID() As String
        Get
            Return Me.subscriberIDField
        End Get
        Set
            Me.subscriberIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property CertificateID() As String
        Get
            Return Me.certificateIDField
        End Get
        Set
            Me.certificateIDField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property ESessionKey() As Byte()
        Get
            Return Me.eSessionKeyField
        End Get
        Set
            Me.eSessionKeyField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SubscriberMessageID() As String
        Get
            Return Me.subscriberMessageIDField
        End Get
        Set
            Me.subscriberMessageIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property InformationExchangeVersion() As String
        Get
            Return Me.informationExchangeVersionField
        End Get
        Set
            Me.informationExchangeVersionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property MessageName() As String
        Get
            Return Me.messageNameField
        End Get
        Set
            Me.messageNameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property TimeSent() As Date
        Get
            Return Me.timeSentField
        End Get
        Set
            Me.timeSentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property MessageContent() As Byte()
        Get
            Return Me.messageContentField
        End Get
        Set
            Me.messageContentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.iru.org")>  _
Partial Public Class TIREPDG2BUploadAck
    
    Private hostIDField As String
    
    Private subscriberMessageIDField As String
    
    Private returnCodeField As Integer
    
    Private returnCodeReasonField As Integer
    
    Private returnCodeReasonFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property HostID() As String
        Get
            Return Me.hostIDField
        End Get
        Set
            Me.hostIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property SubscriberMessageID() As String
        Get
            Return Me.subscriberMessageIDField
        End Get
        Set
            Me.subscriberMessageIDField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ReturnCode() As Integer
        Get
            Return Me.returnCodeField
        End Get
        Set
            Me.returnCodeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property ReturnCodeReason() As Integer
        Get
            Return Me.returnCodeReasonField
        End Get
        Set
            Me.returnCodeReasonField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ReturnCodeReasonSpecified() As Boolean
        Get
            Return Me.returnCodeReasonFieldSpecified
        End Get
        Set
            Me.returnCodeReasonFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")>  _
Public Delegate Sub TIREPDG2BCompletedEventHandler(ByVal sender As Object, ByVal e As TIREPDG2BCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class TIREPDG2BCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As TIREPDG2BUploadAck
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),TIREPDG2BUploadAck)
        End Get
    End Property
End Class
