//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTSDotNETClient.ElectronicGuaranteeInformationServiceWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EGISQueryType", Namespace="http://rts.iru.org/EGIS")]
    [System.SerializableAttribute()]
    public partial class EGISQueryType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubscriberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EGISQueryParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Query_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubscriberID {
            get {
                return this.SubscriberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriberIDField, value) != true)) {
                    this.SubscriberIDField = value;
                    this.RaisePropertyChanged("SubscriberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] EGISQueryParams {
            get {
                return this.EGISQueryParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.EGISQueryParamsField, value) != true)) {
                    this.EGISQueryParamsField = value;
                    this.RaisePropertyChanged("EGISQueryParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Query_ID {
            get {
                return this.Query_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Query_IDField, value) != true)) {
                    this.Query_IDField = value;
                    this.RaisePropertyChanged("Query_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EGISResponseType", Namespace="http://rts.iru.org/EGIS")]
    [System.SerializableAttribute()]
    public partial class EGISResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ESessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EGISResponseParamsField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Query_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MessageTag {
            get {
                return this.MessageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageTagField, value) != true)) {
                    this.MessageTagField = value;
                    this.RaisePropertyChanged("MessageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] ESessionKey {
            get {
                return this.ESessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ESessionKeyField, value) != true)) {
                    this.ESessionKeyField = value;
                    this.RaisePropertyChanged("ESessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] EGISResponseParams {
            get {
                return this.EGISResponseParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.EGISResponseParamsField, value) != true)) {
                    this.EGISResponseParamsField = value;
                    this.RaisePropertyChanged("EGISResponseParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Query_ID {
            get {
                return this.Query_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Query_IDField, value) != true)) {
                    this.Query_IDField = value;
                    this.RaisePropertyChanged("Query_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rts.iru.org/EGIS", ConfigurationName="ElectronicGuaranteeInformationServiceWS.EGISClassSoap")]
    public interface EGISClassSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (EGISResponse) of message EGISQueryResponse does not match the default value (EGISQuery)
        [System.ServiceModel.OperationContractAttribute(Action="http://rts.iru.org/EGIS/EGISQuery", ReplyAction="*")]
        RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryResponse EGISQuery(RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EGISQuery", WrapperNamespace="http://rts.iru.org/EGIS", IsWrapped=true)]
    public partial class EGISQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/EGIS", Order=0)]
        public RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryType su;
        
        public EGISQueryRequest() {
        }
        
        public EGISQueryRequest(RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryType su) {
            this.su = su;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EGISResponse", WrapperNamespace="http://rts.iru.org/EGIS", IsWrapped=true)]
    public partial class EGISQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rts.iru.org/EGIS", Order=0)]
        public RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISResponseType EGISResult;
        
        public EGISQueryResponse() {
        }
        
        public EGISQueryResponse(RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISResponseType EGISResult) {
            this.EGISResult = EGISResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EGISClassSoapChannel : RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISClassSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EGISClassSoapClient : System.ServiceModel.ClientBase<RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISClassSoap>, RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISClassSoap {
        
        public EGISClassSoapClient() {
        }
        
        public EGISClassSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EGISClassSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EGISClassSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EGISClassSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryResponse RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISClassSoap.EGISQuery(RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryRequest request) {
            return base.Channel.EGISQuery(request);
        }
        
        public RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISResponseType EGISQuery(RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryType su) {
            RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryRequest inValue = new RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryRequest();
            inValue.su = su;
            RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISQueryResponse retVal = ((RTSDotNETClient.ElectronicGuaranteeInformationServiceWS.EGISClassSoap)(this)).EGISQuery(inValue);
            return retVal.EGISResult;
        }
    }
}
